version: "3"
services:
  drone:
    image: drone/drone:1.10.1
    restart: always
    volumes:
      - drone:/var/lib/drone
    ports:
      - "81:80"
    environment:
      - DRONE_SERVER_HOST=${VPS_IP}:81
      - DRONE_SERVER_PROTO=http
      - DRONE_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${RPC_SECRET}
      - DRONE_USER_CREATE=username:${ADMIN_USERNAME},admin:true
  drone-agent:
    image: drone/drone-runner-docker:1.6.3
    restart: always
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone:80
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=${RPC_SECRET}
volumes:
  drone: {}